// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJgLexED5HdRg4t4eFp5M_HH8Gc6-z2U',
    appId: '1:978663383814:web:907c4d2873033afdfdf487',
    messagingSenderId: '978663383814',
    projectId: 'cabme-demo-b9c29',
    authDomain: 'cabme-demo-b9c29.firebaseapp.com',
    storageBucket: 'cabme-demo-b9c29.appspot.com',
    measurementId: 'G-F63BKFMMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIUiL9d4LTwSjvQbJmlNOg128V5T3fTKY',
    appId: '1:978663383814:android:a5870081ed3ee607fdf487',
    messagingSenderId: '978663383814',
    projectId: 'cabme-demo-b9c29',
    storageBucket: 'cabme-demo-b9c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlishTUK_vBSzWQR6dpLmMn1nL7cV2VZ4',
    appId: '1:978663383814:ios:da40249f5907aae1fdf487',
    messagingSenderId: '978663383814',
    projectId: 'cabme-demo-b9c29',
    storageBucket: 'cabme-demo-b9c29.appspot.com',
    iosBundleId: 'com.myriad.yegasigur.driver',
  );
}
